PalletPlus.Website/Controllers/AuthenticationController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using AttributeRouting.Web.Mvc;
using nTrack.Core.Utilities;
using nTrack.Data.Indices;
using PalletPlus.Website.ViewModels;

namespace PalletPlus.Website.Controllers
{
    public class AuthenticationController : Controller
    {
        readonly ICryptographyService _cryptographyService;

        public AuthenticationController(ICryptographyService cryptographyService)
        {
            _cryptographyService = cryptographyService;
        }

        [GET("Authentication/Login")]
        public ActionResult Login()
        {
            if (Request.IsAuthenticated)
            {
                //FormsAuthentication.RedirectFromLoginPage(User.Identity.Name,);
            }

            return View("Login", new PageViewModel());
        }

        [POST("Authentication/Login")]
        public ActionResult Login(PageViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.Login))
            {
                ModelState.AddModelError("Login", "You must provide an email for authentication!");
                viewModel.Password = string.Empty;
                return View(viewModel);
            }

            using (var session = MvcApplication.SystemStore.OpenSession())
            {
                var user = session.Query<UserIndex.Result, UserIndex>()
                                    .SingleOrDefault(
                                        x =>
                                        x.Email == viewModel.Login &&
                                        x.Password == _cryptographyService.GetMD5Hash(viewModel.Password));

                if (user == null)
                {
                    ModelState.AddModelError("Login", "Login or password incorrect.");
                    viewModel.Password = string.Empty;
                    return View(viewModel);
                }

                FormsAuthentication.SetAuthCookie(user.UserKey.ToString(), viewModel.RememberMe);

                FormsAuthentication.RedirectFromLoginPage(user.UserKey.ToString(), viewModel.RememberMe);
            }
            return null;
        }

        [GET("Authentication/Logout")]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

PalletPlus.Website/Views/Shared/_FooterPartial.cshtml
@using PalletPlus.Website
<footer>
    <span>&copy; 2012 nTrack Pty Ltd. All Rights Reserved.</span><span style="float: right">v. @MvcApplication.Version</span>
</footer>

PalletPlus.Website/Views/Shared/_Layout.cshtml
@{
    string loginPartial = ViewBag.LoginPartial ?? "_LoginPartial";
}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Pallet Plus - @ViewBag.Title </title>
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/Kendo/css")
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("Styles", false)
        
        <style type="text/css">
            body {
                padding-bottom: 20px;
            }
            .content {
                padding-top: 100px;
            }
            .sidebar-nav {
                padding: 5px 0;
            }
        </style>
        @RenderSection("Scripts", false)
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container" style="padding-top: 5px;padding-bottom: 5px;">
                    <a href="/">
                        <img class="pull-left" id="ntrackLogo" src="/Content/UI/ntrack-pp-logo.png">
                    </a>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div style="padding-top: 6px;">
                            @Html.Partial(loginPartial)
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="content container">
            @RenderBody()
            <hr/>@Html.Partial("_FooterPartial")
        </div>
        @*<div class="container footer"></div>*@
    </body>
</html>

PalletPlus.Website/Views/Shared/_Login.cshtml
@model PageViewModel

@using (Html.BeginForm("Login", "Authentication", new { ReturnUrl = Request.QueryString["ReturnUrl"] }, FormMethod.Post, new { @class = "form-horizontal", autocomplete="off" }))
{
    <div class="field-container">
        <label id="email-label" for="email-input">Email:</label>
        @Html.TextBoxFor(vm => vm.Login, new {id = "email-input", @class = "text-input"})
    </div>
    <div class="field-container">
        <label id="password-label" for="password-input">Password:</label>
        @Html.PasswordFor(vm => vm.Password, new {id = "password-input", @class = "text-input"})
    </div>
    <div class="field-container" style="padding-top: 5px;">
        <label for="remember-me-input" class="checkbox">
        @Html.CheckBoxFor(vm => vm.RememberMe, new {id = "remember-me-input", @class="checkbox"}) Remember me</label>
    </div>
    <div class="buttons-container">
        <input type="submit" value="Login" />
    </div>
}