PalletPlus.Website/Areas/Admin/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AttributeRouting.Web.Mvc;
using nTrack.Data.Extenstions;
using nTrack.Data.Indices;
using nTrack.Extension;
using PalletPlus.Data;
using PalletPlus.Data.Indices;
using PalletPlus.Messages.Commands.Site;
using PalletPlus.Website.Areas.Admin.ViewModels.Site;
using PalletPlus.Website.Services;
using Raven.Client;
using Raven.Client.Linq;
using Account = PalletPlus.Data.Account;

namespace PalletPlus.Website.Areas.Admin.Controllers
{

    public class SiteController : AdminBaseController
    {
        readonly IDocumentSession _session;

        public SiteController(IDocumentSession session, IThreadingService threadingService)
            : base(threadingService)
        {
            _session = session;
        }

        [GET("Sites")]
        public ActionResult Index(bool showDeleted = false)
        {
            ViewBag.ShowDeleted = showDeleted;
            return View(GetSites(showDeleted));
        }

        [GET("Site/Create")]
        public ActionResult Create()
        {
            var vm = new SiteViewModel();

            vm.ComboboxCountries = GetCountries();
            return View(vm);
        }

        [POST("Site/Create")]
        public ActionResult Create(SiteViewModel site)
        {
            //TODO: write a static index
            var siteEntity = _session.Query<Site>().FirstOrDefault(x => x.CompanyName == site.SiteName);
            if (siteEntity != null)
            {
                Failure("A site with that name already exists.");
                site.ComboboxCountries = GetCountries();
                site.SiteName = string.Empty;
                return View(site);
            }

            site.SiteId = Guid.NewGuid();
            Bus.Send<CreateSite>(cmd =>
                {
                    cmd.SiteId = site.SiteId;
                    cmd.Name = site.SiteName;
                    cmd.AddressLine1 = site.AddressLine1;
                    cmd.AddressLine2 = site.AddressLine2;
                    cmd.Suburb = site.Suburb;
                    cmd.State = site.State;
                    cmd.Postcode = site.Postcode;
                    cmd.Country = site.Country;
                });

            if (site.IsPTAEnabled)
            {
                Bus.Send(new UpdatePTAInfo
                {
                    IsEnabled = site.IsPTAEnabled,
                    SequenceNumber = site.PTASequenceNumber,
                    SiteId = site.SiteId,
                    Suffix = site.Suffix
                });
            }

            ThreadingService.ObjectCreated<Site>(site.SiteId);
            RecordCreated("details");

            return RedirectToAction("Edit", new { id = site.SiteId });
        }

        [GET("Site/{id}")]
        public ActionResult Edit(Guid id)
        {
            var site = _session.Load<Site>(id);
            var vm = new SiteEditViewModel();

            if (site != null)
            {
                if (Request.QueryString.Get("Grid-filter") != null)
                    SetTabValue("partners");

                var suppliers = _session.Query<Supplier>(typeof(SupplierIndex).Name);

                var account = _session.Load<Account>(Identity.AccountId);

                var sitePartners = _session.Query<Partner>(typeof(PartnerIndex).Name)
                    .Where(x => !x.IsDeleted && x.Sites.Any(y => y == site.IdString));

                var users = new List<UserIndex.Result>();
                var countries = GetCountries();

                using (var session = MvcApplication.SystemStore.OpenSession())
                {
                    users = session.Query<UserIndex.Result, UserIndex>()
                        .Where(x => x.AccountId == Identity.AccountId.ToStringId<Account>())
                        .ToList();
                }

                vm = new SiteEditViewModel(site, suppliers.ToList(), account.Suppliers, sitePartners.ToList(), users, countries);
                //    vm = Mapper.Map<SiteEditViewModel>(site);
                //GetSuppliers(ref vm, site);
                //GetPartners(ref vm, site);
                //GetUsers(ref vm, site);
                //  vm.ComboboxCountries = GetCountries();

                return View(vm);
            }

            Failure("Couldn't load entity.");
            return View(vm);
        }

        [POST("Site/{id}")]
        public ActionResult Edit(SiteEditViewModel site)
        {
            var siteEntity = _session.Query<Site>()
                .FirstOrDefault(x => x.CompanyName == site.SiteName && site.SiteId != x.Id);

            var sitee = _session.Load<Site>(site.SiteId);

            if (sitee.IsPTAEnabled != site.IsPTAEnabled || sitee.PTASequenceNumber != site.PTASequenceNumber || sitee.PTASuffix != site.Suffix)
            {
                if (site.IsPTAEnabled)
                {
                    Bus.Send(new UpdatePTAInfo()
                                 {
                                     IsEnabled = site.IsPTAEnabled,
                                     SequenceNumber = site.PTASequenceNumber,
                                     SiteId = site.SiteId,
                                     Suffix = site.Suffix
                                 });
                }
                else
                {
                    Bus.Send(new UpdatePTAInfo()
                    {
                        IsEnabled = site.IsPTAEnabled,
                        SequenceNumber = sitee.PTASequenceNumber,
                        SiteId = sitee.Id,
                        Suffix = sitee.PTASuffix
                    });
                }
            }

            if (siteEntity != null)
            {
                Failure("A site with that name already exists.");
                return RedirectToAction("Edit", new { id = site.SiteId });
            }

            Bus.Send<UpdateSite>(cmd =>
            {
                cmd.SiteId = site.SiteId;
                cmd.Name = site.SiteName;
                cmd.AddressLine1 = site.AddressLine1;
                cmd.AddressLine2 = site.AddressLine2;
                cmd.Suburb = site.Suburb;
                cmd.State = site.State;
                cmd.Postcode = site.Postcode;
                cmd.Country = site.Country;
            });

            //ThreadingService.ObjectUpdated<Site>(site.SiteId, UtcNow);

            RecordUpdated("details");

            return RedirectToAction("Edit", new { id = site.SiteId });
        }

        [GET("Site/Delete/{id}")]
        public ActionResult Delete(Guid id, bool showDeleted)
        {
            Bus.Send<DeleteSite>(cmd => { cmd.SiteId = id; });

            ThreadingService.ObjectDeleted<Site>(id);

            return RedirectToAction("Index", SetRouteValues(showDeleted));
        }

        [GET("Site/{id}/Undelete")]
        public ActionResult Undelete(Guid id, bool showDeleted)
        {
            Bus.Send<UndeleteSite>(cmd => cmd.SiteId = id);

            ThreadingService.ObjectUndeleted<Site>(id);

            return RedirectToAction("Index", SetRouteValues(showDeleted));
        }

        [POST("Site/{id}/AddSupplier")]
        public ActionResult AddSupplier(SiteEditViewModel site)
        {
            if (site.SupplierVM.SupplierId.IsEmpty())
            {
                Failure("suppliers", "Please choose supplier from the list of available items.");
                return RedirectToAction("Edit", new { id = site.SiteId });
            }

            if (!ValidateAccountNumberUniquiness(site.SiteId, site.SupplierVM.AccountNumber))
                return RedirectToAction("Edit", new { id = site.SiteId });

            site.SupplierVM.SupplierName = _session.Load<Supplier>(site.SupplierVM.SupplierId).CompanyName;

            Bus.Send<AddSupplierToSite>(cmd =>
                {
                    cmd.SiteId = site.SiteId;
                    cmd.SupplierId = site.SupplierVM.SupplierId;
                    cmd.SupplierName = site.SupplierVM.SupplierName;
                    cmd.SupplierAccountNumber = site.SupplierVM.AccountNumber;
                    cmd.Prefix = site.SupplierVM.Prefix;
                    cmd.Suffix = site.SupplierVM.Suffix;
                    cmd.SequenceNumber = site.SupplierVM.SequenceStartNumber;
                });

            ThreadingService.ObjectUpdated<Site>(site.SiteId, DateTime.UtcNow);
            RecordUpdated("suppliers");

            return RedirectToAction("Edit", new { id = site.SiteId });
        }

        [POST("Site/{id}/EditSupplier")]
        public ActionResult EditSupplier(SiteSupplierEditViewModel site)
        {
            Bus.Send<UpdateSiteSupplier>(cmd =>
                {
                    cmd.SiteId = site.SiteId;
                    cmd.SupplierId = site.SupplierId;
                    cmd.Prefix = site.Prefix;
                    cmd.Suffix = site.Suffix;
                    cmd.SequenceStartNumber = site.SequenceStartNumber;
                });

            ThreadingService.ObjectUpdated<Site>(site.SiteId, DateTime.UtcNow);
            RecordUpdated("suppliers");

            return RedirectToAction("Edit", new { id = site.SiteId });
        }

        [POST("Site/{id}/OverrideSupplier")]
        public ActionResult OverrideSupplier(SiteSupplierEditViewModel site)
        {
            if (!ValidateAccountNumberUniquiness(site.SiteId, site.SupplierAccountNumber))
                return RedirectToAction("Edit", new { id = site.SiteId });

            //var now = Bus.SendMap<AddSupplierToSite>(site);

            Bus.Send<AddSupplierToSite>(cmd =>
                {
                    cmd.SiteId = site.SiteId;
                    cmd.SupplierId = site.SupplierId;
                    cmd.SupplierName = site.SupplierName;
                    cmd.SupplierAccountNumber = site.SupplierAccountNumber;
                    cmd.Prefix = site.Prefix;
                    cmd.Suffix = site.Suffix;

PalletPlus.Website/Areas/Admin/Views/Shared/_FooterPartial.cshtml
@using PalletPlus.Website
<footer>
  <span>&copy; 2012 nTrack Pty Ltd. All Rights Reserved.</span><span style="float: right">v. @MvcApplication.Version</span>
</footer>

PalletPlus.Website/Areas/Admin/Views/Shared/_Layout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string sideBarPartial = ViewBag.SidebarPartial ?? "_SidebarPartial";
}

 
<div class="row">
    <div class="span3">
        @*@Html.Partial("_SidebarPartial")*@
        @Html.Partial(sideBarPartial)
    </div>
    @RenderBody()
    <script>
        $("#State").focusout(function () {
            $("#State").val($("#State").val().toUpperCase());
        });
    </script>      
</div>

@section Scripts
{
     @Scripts.Render("~/bundles/kendo")
     @Scripts.Render("~/bundles/nTrack")
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="@(Url.Content("~/Content/tagit/js/tag-it.min.js"))"></script>



}

@section Styles
{

    <style type="text/css">
        label {
            width: 100px;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="@(Url.Content("~/Content/tagit/css/jquery.tagit.css"))"/>
    <link rel="stylesheet" type="text/css" href="@(Url.Content("~/Content/tagit/css/tagit.ui-zendesk.css"))"/>
}

PalletPlus.Website/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header"><div class="nav-list-icon-dashboard"></div>Dashboard</li>
        <li id="BalanceDashboard"><a href="@Url.Action("Index", "BalanceDashboard", new { area="Admin" })">Balance Dashboard</a></li>
        <li id="MovementDashboard"><a href="@Url.Action("Index", "MovementDashboard", new { area="Admin" })">Movement Dashboard</a></li>
        <li id="ExchangesDashboard"><a href="@Url.Action("Index", "ExchangesDashboard", new { area="Admin" })">Exchanges Dashboard</a></li>

        <li class="nav-header"><div class="nav-list-icon-operation"></div>Operation</li>
        <li id="Reconciliations"><a href="@Url.Action("Index", "Reconciliation", new { area="Admin" })">Reconciliation</a></li>
        <li id="Correction"><a href="@Url.Action("Index", "CorrectionRequests", new { area="Admin" })">Corrections</a></li>
        <li id="Partners"><a href="@Url.Action("Index", "Partner", new { area="Admin"})">Partners</a></li>
        @*<li id="Transporters"><a href="@Url.Action("Index", "Transporter", new { area = "Admin" })">TRANSPORTERS</a></li>*@
        

        <li class="nav-header"><div class="nav-list-icon-utility"></div>Utility</li>
        <li id="Company"><a href="@Url.Action("Index", "Company", new { area="Admin" })">Company Details</a></li>
        <li id="Suppliers"><a href="@Url.Action("Index", "Supplier", new { area="Admin" })">Suppliers</a></li>
        <li id="Sites"><a href="@Url.Action("Index", "Site", new { area="Admin" })">Sites</a></li>
        
        <li class="nav-header"><div class="nav-list-icon-tools"></div>Tools</li>
        <li id="exports"><a href="@Url.Action("Index", "ExportMovement", new { area = "Admin" })">Export Movements</a></li>
        <li id="imports"><a href="@Url.Action("Index", "ImportSupplierInvoice", new { area = "Admin" })">Import Invoices</a></li>
        @*<li id="ImportPartners"><a href="@Url.Action("ImportPartners", "ImportPartners", new { area="Admin" })">Import Partners</a></li>*@
        
    </ul>
</div>

<style scoped>
    .well {
        margin-right: 15px;
    }
</style>